const test=require('node:test'); const assert=require('node:assert'); const request=require('node:http');
process.env.DATABASE_PATH=':memory:'; process.env.SESSION_SECRET='x'.repeat(40); process.env.STRIPE_SECRET_KEY='sk_test_dummy'; process.env.STRIPE_WEBHOOK_SECRET='whsec_dummy'; process.env.PAYMENT_MIN_CENTS='100'; process.env.PAYMENT_MAX_CENTS='4000000';
const {getDb}=require('../lib/db'); const p=require('../lib/payments'); const app=require('../server');
const db=getDb();
function makeReq(over={}){const raw=p.token(), n=p.now(); db.prepare(`insert into payment_requests(publicTokenHash,clientName,clientEmail,amountCents,currency,reference,clientDescription,paymentCategory,allowedPaymentMethods,status,expiresAt,createdAt,updatedAt) values(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(p.hashToken(raw),'Client','c@example.com',750000,'usd','INV-1','Short description','earned_fee','both','active',new Date(Date.now()+86400000).toISOString(),n,n); return {raw,id:db.prepare('select last_insert_rowid() id').get().id};}
test('tokens are 128+ bits and only hashes are stored',()=>{const t=p.token(); assert.ok(t.length>20); const h=p.hashToken(t); assert.notEqual(t,h); assert.equal(h.length,64);});
test('amounts parse to integer cents',()=>{assert.equal(p.centsFromDollars('7500.25'),750025); assert.throws(()=>p.centsFromDollars('1.234'));});
test('expired/revoked/paid links are inactive',()=>{const {id}=makeReq(); assert.ok(p.isActive(db.prepare('select * from payment_requests where id=?').get(id))); db.prepare("update payment_requests set status='paid' where id=?").run(id); assert.equal(p.isActive(db.prepare('select * from payment_requests where id=?').get(id)),false);});
test('client page does not show internal notes',async()=>{const {raw,id}=makeReq(); db.prepare('update payment_requests set internalNote=? where id=?').run('SECRET INTERNAL NOTE',id); const srv=app.listen(0); const port=srv.address().port; const body=await new Promise((resolve,reject)=>request.get(`http://127.0.0.1:${port}/pay/${raw}`,r=>{let b=''; r.on('data',c=>b+=c); r.on('end',()=>resolve(b));}).on('error',reject)); srv.close(); assert.ok(!body.includes('SECRET INTERNAL NOTE')); assert.ok(body.includes('Stripe'));});
test('unsupported method rejected before Stripe',async()=>{const {raw}=makeReq(); const srv=app.listen(0); const port=srv.address().port; const res=await fetch(`http://127.0.0.1:${port}/api/payments/${raw}/checkout`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({method:'wire',amountCents:1,clientName:'Bad'})}); srv.close(); assert.equal(res.status,400);});
test('invalid webhook signatures are rejected',async()=>{const srv=app.listen(0); const port=srv.address().port; const res=await fetch(`http://127.0.0.1:${port}/api/stripe/webhook`,{method:'POST',headers:{'content-type':'application/json','stripe-signature':'bad'},body:'{}'}); srv.close(); assert.equal(res.status,400);});
